name       : haskell-async
version    : 2.2.4
release    : 7
source     :
    # Revision 3
    - https://hackage.haskell.org/package/async-2.2.4/async-2.2.4.tar.gz : 484df85be0e76c4fed9376451e48e1d0c6e97952ce79735b72d54297e7e0a725
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides a higher-level interface over threads
description: |
    This package provides a higher-level interface over threads
builddeps  :
    - ghc-devel
    - haskell-hashable-devel
rundeps    :
    - devel :
      - haskell-hashable-devel
setup      : |
    cp $pkgfiles/3.cabal async.cabal
    %haskell_configure
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
