name       : haskell-async
version    : 2.1.0
release    : 2
source     :
    - https://github.com/simonmar/async/archive/2.1.0.tar.gz : 799d1ec46e3cdda4dccd2cad566d8b9134e40663f2cc7a980edd854cdca6803a
license    : BSD-3-Clause
component  : programming
summary    : This package provides a higher-level interface over threads
description: |
    This package provides a higher-level interface over threads
builddeps  :
    - ghc
    - haskell-stm
setup      : |
    sudo ghc-pkg recache
    ghc -threaded Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --datadir=/usr/share \
                      --sysconfdir=/etc \
                      --libexecdir=/usr/lib64/cabal \
                      --libsubdir="\$compiler/\$pkgid"
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 async-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/async-$version.conf
