name       : haskell-async
version    : 2.2.2
release    : 6
source     :
    - https://hackage.haskell.org/package/async-2.2.2/async-2.2.2.tar.gz : 4b4ab1ac82c45144d82c6daf6cb6ba45eab9957dad44787fa5e869e23d73bbff
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides a higher-level interface over threads
description: |
    This package provides a higher-level interface over threads
builddeps  :
    - haskell-cabal-install
    - haskell-hashable-devel
rundeps    :
    - devel:
        - haskell-hashable-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
