name       : haskell-async
version    : 2.1.0
release    : 4
source     :
    - https://github.com/simonmar/async/archive/2.1.0.tar.gz : 799d1ec46e3cdda4dccd2cad566d8b9134e40663f2cc7a980edd854cdca6803a
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides a higher-level interface over threads
description: |
    This package provides a higher-level interface over threads
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-stm
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
